# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to=utils.get_file_path)),
                ('price', models.CharField(max_length=30)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
