# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
